print("******************************")
print("= NAMA    : BAGAS ARI PRADANA ")
print("= NIM     : 312110485         ")
print("= KELAS   : TI.21 C.5         ")
print("******************************")

print("Masukan nama lengakp : ")
Namalengkap=input()
print("Masukan nama panggilan : ")
panggilan=input()
print("Masukan NPM : ")
npm=int(input())
print("Masukan tempat lahir : ")
pob=input()
print("Masukan tanggal lahir : ")
tanggal=int(input())
print("Masukan bulan lahir : ")
bulan=input()
print("Masukan tahun lahir : ")
tahun=int(input())
print("Masukan no.telpon : ")
no=int(input())
print("Masukan alamat : ")
alamat=input()

dob=2021-tahun

print("\n\n Assalamu'alaikum. ")
print(f"Let me introduce myself, my name is {Namalengkap}, but you can call me {panggilan}, my NPM {npm}, I was born in {pob} and i am {dob} years old, I am very glad if you want to invite my house in {alamat}, So don't forget to call me before with the number {no}, \n\n Thank you ")
